# Use postgres/example user/password credentials
version: '3.1'

services:
  react:
    build: ./webUI/
    ports:
      - 8080:8080
    restart: always
  django:
    build: ./backend/backend/
    ports:
      - 8000:8000
    restart: always