# Use postgres/example user/password credentials
version: '3.1'

services:
  react:
    build: ./webUI/
    ports:
      - 8080:8080
    restart: always
    labels:
      kompose.service.expose: true
  django:
    build:
      context: ./backend/backend/
      args:
        MYSQL_USERNAME: ${MYSQL_USERNAME}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_HOSTNAME: ${MYSQL_HOSTNAME}
        MYSQL_DB: ${MYSQL_DB}
        MYSQL_PORT: ${MYSQL_PORT}
    ports:
      - 8000:8000
    restart: always
    environment:
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_PORT=${MYSQL_PORT}
